### ISSUE TITLE
邮箱注册不了啊

### ISSUE THREAD

**Issue by prinkangkang** [b2stry/mytwitter#15]

**Comment by prinkangkang** [comment]
解决了 把xmlHttp.open("GET", "/mytwitter/user.do?method=checkaite&aite=" + txt, false);改成xmlHttp.open("GET", "user.do?method=checkaite&aite=" + txt, false);

**Comment by prinkangkang** [comment]
有一说一 代码还是有很多小错误的....

**Comment by sana-mine** [comment]
> 解决了 把xmlHttp.open("GET", "/mytwitter/user.do?method=checkaite&aite=" + txt, false);改成xmlHttp.open("GET", "user.do?method=checkaite&aite=" + txt, false);

请问这一行修改了是什么意思呢?

**Comment by prinkangkang** [comment]
> 能具体一下改哪个文件下的嘛？

都改了 这个是请求的时候的路径问题 把所有的mytwitter删掉就好了

**Comment by dasdjkash** [comment]
好了，太感谢啦
