### ISSUE TITLE
请教几个问题：

### ISSUE THREAD

**Issue by PBlithe** [b2stry/mytwitter#2]
你这个东西是基于什么写的呢？还是都是自己手打的？要具备哪些知识能写出这么一个网页来。

**Comment by PBlithe** [comment]
怎么样才能访问网站呢？

**Comment by b2stry** [comment]
前端是HTML、CSS、JS，JS方面用的JQuery，后端就是用的原生的Servlet写的。写前端静态页面的话学网页三剑客：HTML、CSS、JS就可以啊。访问的话，我之前部署的那个服务器到期了，后来就没弄了，你可以把代码clone一下，打个war包部署到Tomcat。

**Comment by PBlithe** [comment]
> 前端是HTML、CSS、JS，JS方面用的JQuery，后端就是用的原生的Servlet写的。写前端静态页面的话学网页三剑客：HTML、CSS、JS就可以啊。访问的话，我之前部署的那个服务器到期了，后来就没弄了，你可以把代码clone一下，打个war包部署到Tomcat。

谢谢啦
