### ISSUE TITLE
测试地址

### ISSUE THREAD

**Issue by ruanwenjun** [b2stry/mytwitter#3]
测试地址好像挂啦？？？

**Comment by b2stry** [comment]
是的，之前那个阿里云服务器到期了 = =

**Comment by lyk1576070851** [comment]
你好，请问一下jdk是1.7还是1.8的呢，Tomcat服务器是什么版本的呢，我这边一直有一些错误，是可以运行出来，但是控制台很多错误呢。谢谢回复

**Comment by b2stry** [comment]
> 你好，请问一下jdk是1.7还是1.8的呢，Tomcat服务器是什么版本的呢，我这边一直有一些错误，是可以运行出来，但是控制台很多错误呢。谢谢回复

jdk是1.8，tomcat是8.5的，我修改了点东西，你pull之后再试下。
